# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(default=None, max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='action',
            name='slug',
            field=models.CharField(default=None, max_length=60, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='action',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.ActionLanguage'),
        ),
    ]
