# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171004_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=None, max_length=60, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Slug',
                'verbose_name_plural': 'Slugs',
            },
        ),
    ]
