# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_actionslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='slug',
            field=models.ForeignKey(default=None, max_length=60, on_delete=django.db.models.deletion.CASCADE, to='users.ActionSlug'),
        ),
    ]
