# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171004_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(default=None, max_length=60, unique=True, verbose_name='name'),
        ),
    ]
