# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171004_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlanguage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='actionslug',
            name='id',
        ),
        migrations.AlterField(
            model_name='actionlanguage',
            name='name',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actionslug',
            name='slug',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='slug'),
        ),
    ]
