# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171004_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Languages'),
        ),
        migrations.DeleteModel(
            name='ActionLanguage',
        ),
    ]
