# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import main.functions


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171003_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(default=None, max_length=255, upload_to=main.functions.get_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='is main'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=125, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='key_words',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='key_words'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=65, null=True, verbose_name='title'),
        ),
    ]
