# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:05
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import main.functions


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171010_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=main.functions.get_image_path, verbose_name='image'),
        ),
    ]
