# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20171005_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelikes',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='articlelikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='articlelikes',
            unique_together=set([('user', 'article')]),
        ),
        migrations.AlterModelTable(
            name='articlelikes',
            table='blog_article_likes',
        ),
        migrations.RemoveField(
            model_name='articlelikes',
            name='id',
        ),
    ]
