# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171005_0454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlelikes',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='articlelikes',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlelikes',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArticleLikes',
        ),
    ]
