# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_languages'),
        ('blog', '0009_articlelikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Languages'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default=None, max_length=65, verbose_name='title'),
        ),
    ]
