# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_languages'),
        ('blog', '0012_auto_20171005_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='key_words',
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Languages', verbose_name='tags'),
        ),
    ]
