# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171005_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleViewsPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
            ],
            options={
                'db_table': 'article_views_per_day',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Languages', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='articleviewsperday',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
