# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171005_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='articleviewsperday',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='article'),
        ),
    ]
