# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import main.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='username')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='title')),
                ('email', models.EmailField(max_length=40, verbose_name='email')),
                ('text', models.CharField(default=None, max_length=250, verbose_name='text')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'main_message',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='title')),
                ('text', models.TextField(blank=True, default=None, null=True, verbose_name='text')),
                ('image', models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=main.functions.get_image_path, verbose_name='image')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
