# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
