# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import main.functions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171002_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(default=None, max_length=250, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=64, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=main.functions.get_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='title'),
        ),
    ]
