# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171004_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='data',
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date'),
        ),
    ]
