# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171004_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
    ]
